
define([], function() {

    return {

        getValence: function(element) {

            return ({
                "Ac": 3,
                "Ag": 2,
                "Al": 3,
                "Am": 4,
                "Ar": 0,
                "As": 5,
                "At": 7,
                "Au": 5,
                "B": 3,
                "Ba": 2,
                "Be": 2,
                "Bh": 7,
                "Bi": 5,
                "Bk": 4,
                "Br": 7,
                "C": 4,
                "Ca": 2,
                "Cd": 2,
                "Ce": 4,
                "Cf": 4,
                "Cl": 5,
                "Cm": 4,
                "Co": 4,
                "Cr": 6,
                "Cs": 1,
                "Cu": 2,
                "Db": 5,
                "Ds": null,
                "Dy": 3,
                "Er": 3,
                "Es": 4,
                "Eu": 3,
                "F": 1,
                "Fe": 3,
                "Fm": 3,
                "Fr": 3,
                "Ga": 3,
                "Gd": 3,
                "Ge": 4,
                "H": 1,
                "He": 0,
                "Hf": 4,
                "Hg": 2,
                "Ho": 3,
                "Hs": null,
                "I": 7,
                "In": 3,
                "Ir": 6,
                "K": 1,
                "Kr": 2,
                "La": 3,
                "Li": 1,
                "Lr": 3,
                "Lu": 3,
                "Md": 3,
                "Mg": 2,
                "Mn": 4,
                "Mo": 6,
                "Mt": null,
                "N": 3,
                "Na": 1,
                "Nb": 5,
                "Nd": 3,
                "Ne": 0,
                "Ni": 2,
                "No": 3,
                "Np": 6,
                "O": 2,
                "Os": 6,
                "P": 5,
                "Pa": 5,
                "Pb": 4,
                "Pd": 4,
                "Pm": 3,
                "Po": 6,
                "Pr": 4,
                "Pt": 6,
                "Pu": 6,
                "Ra": 2,
                "Rb": 1,
                "Re": 7,
                "Rf": 4,
                "Rg": null,
                "Rh": 6,
                "Rn": 6,
                "Ru": 6,
                "S": 6,
                "Sb": 5,
                "Sc": 3,
                "Se": 6,
                "Sg": 6,
                "Si": 4,
                "Sm": 3,
                "Sn": 4,
                "Sr": 2,
                "Ta": 5,
                "Tb": 3,
                "Tc": 7,
                "Te": 6,
                "Th": 4,
                "Ti": 4,
                "Tl": 3,
                "Tm": 3,
                "U": 6,
                "Uub": null,
                "Uuh": null,
                "Uuo": null,
                "Uup": null,
                "Uuq": null,
                "Uus": null,
                "Uut": null,
                "V": 5,
                "W": 6,
                "Xe": 6,
                "Y": 3,
                "Yb": 3,
                "Zn": 2,
                "Zr": 4

            })[element];
        }

    }

});
